# â•’â•â•â•â•â•â•â•—        â•’â•â•â•â•â•â•â•â•—
# â”‚ â•“â”€â”€â” â•‘â•â•â•â•â•â•â•â•â•—  â•“â”€â”  â•‘
# â”‚ â•šâ•â•â•› â•‘â”€â”€â”  â•“â”€â”€â•œ  â•‘ â”‚  â•‘  RustyTake-Off
# â”‚ â•“â”€â” â•“â•œ  â”‚  â•‘  â”‚  â•‘ â”‚  â•‘  https://github.com/RustyTake-Off
# â”‚ â•‘ â”‚ â•šâ•—  â”‚  â•‘  â”‚  â•šâ•â•›  â•‘
# â””â”€â•œ â””â”€â”€â•œ  â””â”€â”€â•œ  â””â”€â”€â”€â”€â”€â”€â”€â•œ
# Starship config
# Starship docs: https://starship.rs
# Unicode characters: https://unicodes.jessetane.com

"$schema" = 'https://starship.rs/config-schema.json'

# Set prompt format
format = '$os$username@$hostname$directory$python$git_branch$git_status'
add_newline = false

# Change some of the colors
palette = 'custom'

[palettes.custom]
blue = '#4285f4'
orange = '#ffa700'
pink = '#ff71ce'
purple = '#8b00fd'

# Base prompt
[character]
success_symbol = ''
error_symbol = ''

[os]
format = '[$symbol]($style) '
style = 'white bold'
disabled = false

[os.symbols]
Windows = 'î˜ª'
Ubuntu = 'ïŒ›'
Macos = 'ó°€µ'

[username]
format = '[$user]($style)'
style_user = 'blue bold'
style_root = 'red bold'
show_always = true
disabled = false

[hostname]
format = '[$hostname]($style) '
style = 'yellow bold'
ssh_only = false
disabled = false

[directory]
format = 'at [$path]($style)[$read_only]($read_only_style) '
truncation_length = 1
truncation_symbol = 'â€¦/'
read_only = 'ï€£'
read_only_style = 'red'
style = 'cyan bold'
disabled = false

# Git prompt
[git_branch]
format = '\[ [$branch]($style) '
truncation_symbol = 'â€¦/'
style = 'green bold'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)\] '
ahead = 'â‡¡${count} '
behind = 'â‡£${count} '
conflicted = 'âš ${count} '
deleted = 'X${count} '
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count} '
modified = 'M${count} '
renamed = 'R${count} '
staged = 'Â±${count} '
stashed = 'â˜–${count} '
untracked = '?${count} '
up_to_date = ''
style = 'green bold'
disabled = false

# Tools and languages prompts
[python]
format = '\[[$symbol(\($virtualenv\))]($style)\] '
symbol = 'ğ‘ƒğ‘Œ'
style = 'green bold'
disabled = false

[nodejs]
format = '\[[$symbol]($style)\] '
symbol = 'ğ‘ğ‘‚'
style = 'orange bold'
disabled = true

[golang]
format = '\[[($symbol)]($style)\] '
symbol = 'ğºğ‘‚'
style = 'cyan bold'
disabled = true

[rust]
format = '\[[$symbol]($style)\] '
symbol = 'ğŸ¦€'
style = 'red bold'
disabled = true

[kubernetes]
format = '\[[$symbol $context]($style)\] '
symbol = 'â˜¸'
style = 'purple bold'
disabled = true

[terraform]
format = '\[[$symbol]($style)\] '
symbol = 'ğ‘‡ğ¹'
style = 'purple bold'
disabled = true

[azure]
format = '\[[$symbol]($style)\] '
symbol = 'ğ´ğ‘'
style = 'blue bold'
disabled = true

[aws]
format = '\[[$symbol]($style)\] '
symbol = 'ğ´ğ‘Šğ‘†'
style = 'red bold'
disabled = true

[gcloud]
format = '\[[$symbol]($style)\] '
symbol = 'ğºğ¶ğ‘ƒ'
style = 'white bold'
disabled = true
